### ISSUE TITLE
Reconcile inventory attribute names to match ec2 tags

### ISSUE THREAD

**Issue by ashleygould** [CDLUC3/mrt-admin-lambda#12]
This applies to branch inventory

host inventory is based on ec2 tags, which combined form the fully qualified service name (fqsn):
Program
Service
Subservice
Environment

The column and attribute names used in the inventory queries and service inventory input data should match:

System => Service
Subsystem => Subservice

**Comment by terrywbrady** [comment]
System inventory is no longer part of the admin tool.  Closing
